import { User, Session, Meeting, Connection, Note, Report } from '@/types';

// Pre-seeded admin user
export const adminUser: User = {
  id: 'admin-1',
  firstName: 'Abid',
  lastName: 'Admin',
  companyName: 'TBDC',
  companyUID: 'TBDC-001',
  email: 'abid@tbdc.com',
  password: 'admin123',
  role: 'Admin',
  createdAt: new Date('2024-01-01'),
  linkedinUrl: 'https://www.linkedin.com/in/abid-admin',
};

// Sample ACME user
export const acmeUser: User = {
  id: 'user-1',
  firstName: 'John',
  lastName: 'Doe',
  companyName: 'ACME Corp',
  companyUID: 'ACME-001',
  email: 'john@acme.com',
  password: 'user123',
  role: 'User',
  createdAt: new Date('2024-01-15'),
  linkedinUrl: 'https://www.linkedin.com/in/john-doe-acme',
};

export const mockUsers: User[] = [
  adminUser,
  acmeUser,
  {
    id: 'user-2',
    firstName: 'Jane',
    lastName: 'Smith',
    companyName: 'TechCorp',
    companyUID: 'TECH-001',
    email: 'jane@techcorp.com',
    password: 'user123',
    role: 'User',
    createdAt: new Date('2024-01-20'),
    linkedinUrl: 'https://www.linkedin.com/in/jane-smith-techcorp',
  },
];

export const mockSessions: Session[] = [
  {
    id: 'session-1',
    name: 'Digital Transformation Summit',
    date: new Date('2024-02-15T09:00:00'),
    duration: 120,
    type: 'Conference',
    location: 'Main Auditorium',
    description: 'Exploring the future of digital transformation in business.',
    companyUID: 'ACME-001',
    mentorIds: ['conn-1', 'conn-2'],
  },
  {
    id: 'session-2',
    name: 'AI in Healthcare Workshop',
    date: new Date('2024-02-16T14:00:00'),
    duration: 90,
    type: 'Workshop',
    location: 'Room B',
    description: 'Hands-on workshop on implementing AI solutions in healthcare.',
    companyUID: 'ACME-001',
    mentorIds: ['conn-3'],
  },
  {
    id: 'session-3',
    name: 'Startup Pitch Competition',
    date: new Date('2024-02-17T10:00:00'),
    duration: 180,
    type: 'Competition',
    location: 'Innovation Hub',
    description: 'Young entrepreneurs pitch their innovative ideas.',
    companyUID: 'ACME-001',
    mentorIds: ['conn-4'],
  },
];

export const mockMeetings: Meeting[] = [
  {
    id: 'meeting-1',
    title: 'Q1 Strategy Planning',
    date: new Date('2024-02-20T10:00:00'),
    duration: 60,
    type: 'Strategy',
    location: 'Conference Room A',
    description: 'Planning session for Q1 objectives and key results.',
    companyUID: 'ACME-001',
    attendeeIds: ['conn-1', 'conn-2'],
    organizerId: 'user-1',
  },
  {
    id: 'meeting-2',
    title: 'Product Demo Review',
    date: new Date('2024-02-21T15:00:00'),
    duration: 45,
    type: 'Review',
    location: 'Virtual',
    description: 'Review of the latest product demo and feedback collection.',
    companyUID: 'ACME-001',
    attendeeIds: ['conn-3', 'conn-4'],
    organizerId: 'user-1',
  },
  {
    id: 'meeting-3',
    title: 'Partnership Discussion',
    date: new Date('2024-02-22T11:00:00'),
    duration: 90,
    type: 'Partnership',
    location: 'Executive Boardroom',
    description: 'Exploring potential partnership opportunities.',
    companyUID: 'ACME-001',
    attendeeIds: ['conn-1', 'conn-3'],
    organizerId: 'user-1',
  },
];

export const mockConnections: Connection[] = [
  {
    id: 'conn-1',
    firstName: 'Sarah',
    lastName: 'Johnson',
    role: 'CTO',
    type: 'Mentor',
    organization: 'TechVentures',
    bio: 'Experienced technology leader with 15+ years in software development and team management.',
    profileImage: require('@/assets/images/banners/1.png'),
    companyUID: 'ACME-001',
    linkedSessionIds: ['session-1'],
    linkedMeetingIds: ['meeting-1', 'meeting-3'],
    isFavorite: true,
    linkedinUrl: 'https://www.linkedin.com/in/a3azad',
  },
  {
    id: 'conn-2',
    firstName: 'Michael',
    lastName: 'Chen',
    role: 'Product Manager',
    type: 'Customer',
    organization: 'InnovateLab',
    bio: 'Product strategist focused on user-centered design and agile development methodologies.',
    profileImage: require('@/assets/images/banners/2.png'),
    companyUID: 'ACME-001',
    linkedSessionIds: ['session-1'],
    linkedMeetingIds: ['meeting-1'],
    isFavorite: false,
    linkedinUrl: 'https://www.linkedin.com/in/michael-chen-pm',
  },
  {
    id: 'conn-3',
    firstName: 'Dr. Emily',
    lastName: 'Rodriguez',
    role: 'Research Director',
    type: 'EIR',
    organization: 'HealthTech Solutions',
    bio: 'Leading researcher in AI applications for healthcare with multiple published papers.',
    profileImage: require('@/assets/images/banners/3.png'),
    companyUID: 'ACME-001',
    linkedSessionIds: ['session-2'],
    linkedMeetingIds: ['meeting-2', 'meeting-3'],
    isFavorite: false,
    linkedinUrl: 'https://www.linkedin.com/in/dr-emily-rodriguez',
  },
  {
    id: 'conn-4',
    firstName: 'Alex',
    lastName: 'Thompson',
    role: 'Startup Founder',
    type: 'Investor',
    organization: 'GreenTech Innovations',
    bio: 'Environmental entrepreneur developing sustainable technology solutions.',
    companyUID: 'ACME-001',
    linkedSessionIds: ['session-3'],
    linkedMeetingIds: ['meeting-2'],
    isFavorite: false,
    linkedinUrl: 'https://www.linkedin.com/in/alex-thompson-founder',
  },
  {
    id: 'conn-5',
    firstName: 'Lisa',
    lastName: 'Wang',
    role: 'VP of Sales',
    type: 'Customer',
    organization: 'Enterprise Solutions Inc',
    bio: 'Sales executive specializing in B2B enterprise software solutions.',
    companyUID: 'ACME-001',
    linkedSessionIds: [],
    linkedMeetingIds: [],
    isFavorite: false,
  },
  {
    id: 'conn-6',
    firstName: 'David',
    lastName: 'Kumar',
    role: 'Senior Advisor',
    type: 'Mentor',
    organization: 'Innovation Partners',
    bio: 'Strategic advisor with 20+ years experience in scaling technology companies.',
    companyUID: 'ACME-001',
    linkedSessionIds: [],
    linkedMeetingIds: [],
    isFavorite: false,
  },
];

export const mockNotes: Note[] = [
  {
    id: 'note-1',
    connectionId: 'conn-1',
    topic: 'Cloud Architecture',
    content: 'Great insights on cloud architecture. Follow up on the microservices discussion.',
    createdAt: new Date('2024-02-15T16:30:00'),
    companyUID: 'ACME-001',
  },
  {
    id: 'note-2',
    connectionId: 'conn-3',
    topic: 'AI Collaboration',
    content: 'Interested in collaborating on the AI healthcare project. Schedule a follow-up meeting.',
    createdAt: new Date('2024-02-16T17:00:00'),
    companyUID: 'ACME-001',
  },
];

export const mockReports: Report[] = [
  {
    id: 'report-1',
    title: 'Q4 2023 Event Summary',
    type: 'Summary',
    date: new Date('2024-01-31'),
    pdfUrl: 'https://example.com/reports/q4-2023-summary.pdf',
    companyUID: 'ACME-001',
  },
  {
    id: 'report-2',
    title: 'Networking Analytics Report',
    type: 'Analytics',
    date: new Date('2024-02-01'),
    pdfUrl: 'https://example.com/reports/networking-analytics.pdf',
    companyUID: 'ACME-001',
  },
];